export const ScreenName = {
    HomePage: 'Home',
    Types: 'Types',
    Info: 'Info',
    Categories: 'Categories',
    SignIn: 'Sign In',
    SignUp: 'Sign Up',
    Favorite: 'Favorite',
    SearchHome: 'Search Home',
    CustomDrawer:'Custom Drawer', 
    CustomHeader: 'CustomHeader', 
    IconContainer: 'IconContainer', 
    UserProfilePage: 'Profile', 
    Schedule: 'Schedule',
    MainStack: "MainStack",
    EditProfile: "Edit Profile",
    CardInfo: "Card Info",
    SplashScreen: "Splash Screen",
    SlideIntroScreens: "Into Slides",
    searchList: "searchList",
};